### ISSUE TITLE
Ambiguities in some Travel Grant Application Form fields

### ISSUE THREAD

**Issue by gubatron** [researchdao/docs#9]
@k4m4 I've sent a mock travel grant application and I've left a few comments on some fields in which it's not very clear what's expected from the applicant.

Just a word or two on the questions will make it a lot better.

**Comment by k4m4** [comment]
@gubatron I made some changes to the form. Let me know if you think that those changes suffice.

**Comment by gubatron** [comment]
Much better now @k4m4 ! 👍👍
